env:
  global:
    - RUST_BACKTRACE=1

matrix:
  include:
    - name: macos
      os: osx
      addons:
        homebrew:
          packages:
            - gtk+3
      language: rust
      cache: cargo
      rust: stable
      script:
        - cargo build --verbose
        - make test
    - name: linux
      os: linux
      sudo: required
      language: minimal
      services:
        - docker
      script:
        - docker pull andy128k/rust-gtk
        - docker run -d --name rust-gtk-container -v `pwd`:/volume --security-opt seccomp=unconfined andy128k/rust-gtk:latest
        - docker exec -it rust-gtk-container cargo build
        - docker exec -it rust-gtk-container make test
        - docker exec -it rust-gtk-container make coverage
        - bash <(curl -s https://codecov.io/bash)

script:
