name: Release Windows

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-gnu
        default: true
        override: true
    - name: Set PATH
      run: echo "##[add-path]C:\msys64\usr\bin;C:\msys64\mingw64\bin"
    - name: Install dependencies
      run: pacman --noconfirm -S mingw-w64-x86_64-gtk3
    - name: Set PKG_CONFIG_PATH
      run: echo "##[set-env name=PKG_CONFIG_PATH]/mingw64/lib/pkgconfig"
    - name: Set RUSTFLAGS
      run: echo "##[set-env name=RUSTFLAGS]-L C:\msys64\mingw64\lib"
    - name: Build
      run: cargo build --verbose --release
    - name: Make zip
      id: make-zip
      run: |
        VERSION=${{ github.event.release.tag_name }} bash make-win2.sh
        echo ::set-output name=zip-path::archive.zip
        echo ::set-output name=zip-name::archive.zip
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_USER: ${{ secrets.DEPLOY_USER }}
        GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.make-dmg.outputs.zip-path }}
        asset_name: ${{ steps.make-dmg.outputs.zip-name }}
        asset_content_type: application/octet-stream
